services:
  postgres:
    image: postgres:15
    container_name: eventify-postgres
    environment:
      POSTGRES_DB: eventify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: eventify-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      FRONTEND_URL: http://localhost:5173
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/eventify?schema=public
      JWT_SECRET: Rh3inm3t411
      JWT_EXPIRES_IN: 14d
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - postgres

volumes:
  postgres_data:
